In [2]:
import os
import sys
import pyspark
import random
import time
import multiprocessing

import findspark
findspark.init()
findspark.find()

from pyspark.sql import SparkSession
from pyspark.sql import DataFrame, SparkSession, Window
from pyspark.sql.functions import row_number, max, min, col
import pyspark.sql.functions as F

In [4]:
Spark = SparkSession.builder.appName("Tarea 2").getOrCreate()
nombre_app = Spark.sparkContext.appName
print(f"El nombre de la aplicación es: {nombre_app}")

24/10/25 17:20:20 WARN Utils: Your hostname, MacBook-Pro-de-Ricardo.local resolves to a loopback address: 127.0.0.1; using 192.168.5.227 instead (on interface en0)
24/10/25 17:20:20 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/10/25 17:20:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

El nombre de la aplicación es: Tarea 2

In [6]:
df = Spark.read.csv("ENOE.csv", header=True, inferSchema=True)

In [8]:
window_spec = Window.orderBy("ent")
df_with_index = df.select("ent", "sex", "eda", "clase1", "e_con", "n_hij",  "ingocup").withColumn("index", row_number().over(window_spec))
columns = ["index", "ent", "sex", "eda", "clase1", "e_con", "n_hij",  "ingocup"]
df_with_index = df_with_index.select(columns)
df_with_index.show()
total_individuos = df_with_index.select("index").count()
print(f"Total individuos: {total_individuos}")

24/10/25 17:20:28 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:20:28 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:20:28 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-----+---+---+---+------+-----+-----+-------+
|index|ent|sex|eda|clase1|e_con|n_hij|ingocup|
+-----+---+---+---+------+-----+-----+-------+
|    1|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    2|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    3|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    4|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    5|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    6|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    7|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    8|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|    9|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   10|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   11|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   12|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   13|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   14|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   15|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   16|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   17|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   18|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   19|  1|  1|  0|  NULL| NULL| NULL|   NULL|
|   20|  1|  1|  0|  NULL| NULL| NULL|   NULL|
+-----+---+---+---+------+-----+-----+-------+
only showing top 20 rows

Total individuos: 415998

In [68]:
rdd_from_df = df_with_index.rdd

filtered_rdd = rdd_from_df.filter(lambda x: x["clase1"] == 1 and x["n_hij"] != None and x["ingocup"] != None)
filtered_rdd2 = filtered_rdd.filter(lambda x: x["ent"] == 9 or x["ent"] == 19) 
filtered_rows = filtered_rdd2.collect()
filtered_rows

24/10/23 15:08:27 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/23 15:08:27 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/23 15:08:27 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/23 15:08:28 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/23 15:08:28 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

[Row(index=117738, ent=9, sex=2, eda=15, clase1=1, e_con=6, n_hij=0, ingocup=1032),
 Row(index=117756, ent=9, sex=2, eda=15, clase1=1, e_con=6, n_hij=0, ingocup=1290),
 Row(index=117765, ent=9, sex=2, eda=15, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=117825, ent=9, sex=2, eda=16, clase1=1, e_con=6, n_hij=0, ingocup=1935),
 Row(index=117838, ent=9, sex=2, eda=16, clase1=1, e_con=6, n_hij=0, ingocup=1935),
 Row(index=117863, ent=9, sex=2, eda=17, clase1=1, e_con=6, n_hij=0, ingocup=2150),
 Row(index=117878, ent=9, sex=2, eda=17, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=117910, ent=9, sex=2, eda=17, clase1=1, e_con=6, n_hij=1, ingocup=7740),
 Row(index=117933, ent=9, sex=2, eda=18, clase1=1, e_con=6, n_hij=0, ingocup=2580),
 Row(index=117947, ent=9, sex=2, eda=18, clase1=1, e_con=6, n_hij=0, ingocup=2580),
 Row(index=117953, ent=9, sex=2, eda=18, clase1=1, e_con=6, n_hij=0, ingocup=7740),
 Row(index=117954, ent=9, sex=2, eda=18, clase1=1, e_con=6, n_hij=1, ingocup=1720),
 Row(index=117956, ent=9, sex=2, eda=18, clase1=1, e_con=6, n_hij=0, ingocup=5160),
 Row(index=117980, ent=9, sex=2, eda=18, clase1=1, e_con=6, n_hij=0, ingocup=3870),
 Row(index=117989, ent=9, sex=2, eda=18, clase1=1, e_con=6, n_hij=0, ingocup=5400),
 Row(index=117997, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=118007, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=1, ingocup=1032),
 Row(index=118021, ent=9, sex=2, eda=19, clase1=1, e_con=1, n_hij=0, ingocup=6880),
 Row(index=118025, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=1, ingocup=1720),
 Row(index=118027, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=5160),
 Row(index=118036, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=8200),
 Row(index=118039, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=14000),
 Row(index=118047, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118048, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=1, ingocup=3655),
 Row(index=118049, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=3870),
 Row(index=118050, ent=9, sex=2, eda=19, clase1=1, e_con=1, n_hij=1, ingocup=1720),
 Row(index=118055, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=1720),
 Row(index=118061, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118068, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=118070, ent=9, sex=2, eda=19, clase1=1, e_con=6, n_hij=0, ingocup=20640),
 Row(index=118072, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=7200),
 Row(index=118073, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=2, ingocup=10000),
 Row(index=118077, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=860),
 Row(index=118080, ent=9, sex=2, eda=20, clase1=1, e_con=1, n_hij=0, ingocup=7740),
 Row(index=118084, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=4000),
 Row(index=118088, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=118091, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=1720),
 Row(index=118096, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=6880),
 Row(index=118109, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=2150),
 Row(index=118117, ent=9, sex=2, eda=20, clase1=1, e_con=3, n_hij=1, ingocup=7525),
 Row(index=118121, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=8170),
 Row(index=118130, ent=9, sex=2, eda=20, clase1=1, e_con=2, n_hij=2, ingocup=3010),
 Row(index=118131, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=4000),
 Row(index=118139, ent=9, sex=2, eda=20, clase1=1, e_con=1, n_hij=0, ingocup=3010),
 Row(index=118140, ent=9, sex=2, eda=20, clase1=1, e_con=6, n_hij=0, ingocup=6680),
 Row(index=118141, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=4600),
 Row(index=118145, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=6000),
 Row(index=118148, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=5160),
 Row(index=118153, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=7600),
 Row(index=118154, ent=9, sex=2, eda=21, clase1=1, e_con=1, n_hij=1, ingocup=1290),
 Row(index=118155, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=118156, ent=9, sex=2, eda=21, clase1=1, e_con=1, n_hij=1, ingocup=2000),
 Row(index=118159, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118161, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=2580),
 Row(index=118163, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=7000),
 Row(index=118167, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=6800),
 Row(index=118168, ent=9, sex=2, eda=21, clase1=1, e_con=1, n_hij=0, ingocup=8600),
 Row(index=118172, ent=9, sex=2, eda=21, clase1=1, e_con=6, n_hij=0, ingocup=7500),
 Row(index=118192, ent=9, sex=2, eda=21, clase1=1, e_con=1, n_hij=0, ingocup=6200),
 Row(index=118198, ent=9, sex=2, eda=21, clase1=1, e_con=1, n_hij=0, ingocup=8600),
 Row(index=118211, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=12000),
 Row(index=118216, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=6000),
 Row(index=118218, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=25000),
 Row(index=118224, ent=9, sex=2, eda=22, clase1=1, e_con=1, n_hij=1, ingocup=2322),
 Row(index=118229, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=8170),
 Row(index=118240, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=3870),
 Row(index=118243, ent=9, sex=2, eda=22, clase1=1, e_con=1, n_hij=1, ingocup=3010),
 Row(index=118247, ent=9, sex=2, eda=22, clase1=1, e_con=2, n_hij=1, ingocup=4730),
 Row(index=118248, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118259, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=7740),
 Row(index=118265, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=2150),
 Row(index=118269, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=14000),
 Row(index=118270, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=10750),
 Row(index=118281, ent=9, sex=2, eda=22, clase1=1, e_con=6, n_hij=0, ingocup=5805),
 Row(index=118287, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=8000),
 Row(index=118297, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=20000),
 Row(index=118298, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=8600),
 Row(index=118300, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=8600),
 Row(index=118301, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=5160),
 Row(index=118307, ent=9, sex=2, eda=23, clase1=1, e_con=1, n_hij=2, ingocup=6880),
 Row(index=118313, ent=9, sex=2, eda=23, clase1=1, e_con=1, n_hij=0, ingocup=22000),
 Row(index=118314, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=20000),
 Row(index=118317, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=9460),
 Row(index=118323, ent=9, sex=2, eda=23, clase1=1, e_con=2, n_hij=2, ingocup=3440),
 Row(index=118329, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=11610),
 Row(index=118330, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=5590),
 Row(index=118331, ent=9, sex=2, eda=23, clase1=1, e_con=1, n_hij=1, ingocup=16000),
 Row(index=118336, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=2, ingocup=6450),
 Row(index=118338, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=3440),
 Row(index=118342, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=5160),
 Row(index=118357, ent=9, sex=2, eda=23, clase1=1, e_con=6, n_hij=0, ingocup=5000),
 Row(index=118371, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118372, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=2, ingocup=3000),
 Row(index=118373, ent=9, sex=2, eda=24, clase1=1, e_con=5, n_hij=0, ingocup=12000),
 Row(index=118374, ent=9, sex=2, eda=24, clase1=1, e_con=2, n_hij=2, ingocup=2580),
 Row(index=118375, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=8600),
 Row(index=118378, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=14000),
 Row(index=118380, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=118381, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=6300),
 Row(index=118389, ent=9, sex=2, eda=24, clase1=1, e_con=5, n_hij=1, ingocup=4300),
 Row(index=118390, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=5160),
 Row(index=118398, ent=9, sex=2, eda=24, clase1=1, e_con=1, n_hij=1, ingocup=4000),
 Row(index=118403, ent=9, sex=2, eda=24, clase1=1, e_con=2, n_hij=1, ingocup=5400),
 Row(index=118406, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=12000),
 Row(index=118407, ent=9, sex=2, eda=24, clase1=1, e_con=1, n_hij=1, ingocup=8600),
 Row(index=118414, ent=9, sex=2, eda=24, clase1=1, e_con=3, n_hij=1, ingocup=10000),
 Row(index=118417, ent=9, sex=2, eda=24, clase1=1, e_con=1, n_hij=1, ingocup=6000),
 Row(index=118418, ent=9, sex=2, eda=24, clase1=1, e_con=1, n_hij=2, ingocup=6450),
 Row(index=118420, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=4300),
 Row(index=118421, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=12000),
 Row(index=118424, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=7310),
 Row(index=118428, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=16000),
 Row(index=118435, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=14000),
 Row(index=118442, ent=9, sex=2, eda=24, clase1=1, e_con=6, n_hij=0, ingocup=18000),
 Row(index=118450, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=21200),
 Row(index=118452, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=10000),
 Row(index=118455, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=3440),
 Row(index=118456, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=8000),
 Row(index=118459, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=18000),
 Row(index=118461, ent=9, sex=2, eda=25, clase1=1, e_con=1, n_hij=1, ingocup=2150),
 Row(index=118463, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=2150),
 Row(index=118468, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=15000),
 Row(index=118469, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=25000),
 Row(index=118470, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=7500),
 Row(index=118473, ent=9, sex=2, eda=25, clase1=1, e_con=5, n_hij=0, ingocup=1000),
 Row(index=118474, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=2, ingocup=9030),
 Row(index=118481, ent=9, sex=2, eda=25, clase1=1, e_con=1, n_hij=0, ingocup=12900),
 Row(index=118482, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=2, ingocup=3000),
 Row(index=118483, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=2, ingocup=7000),
 Row(index=118486, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=4800),
 Row(index=118495, ent=9, sex=2, eda=25, clase1=1, e_con=1, n_hij=3, ingocup=5590),
 Row(index=118496, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=7525),
 Row(index=118498, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=5000),
 Row(index=118499, ent=9, sex=2, eda=25, clase1=1, e_con=1, n_hij=2, ingocup=3440),
 Row(index=118500, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=16000),
 Row(index=118505, ent=9, sex=2, eda=25, clase1=1, e_con=6, n_hij=0, ingocup=3440),
 Row(index=118514, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=7000),
 Row(index=118516, ent=9, sex=2, eda=26, clase1=1, e_con=1, n_hij=1, ingocup=10750),
 Row(index=118519, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118524, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=14000),
 Row(index=118530, ent=9, sex=2, eda=26, clase1=1, e_con=5, n_hij=0, ingocup=5000),
 Row(index=118541, ent=9, sex=2, eda=26, clase1=1, e_con=1, n_hij=0, ingocup=8000),
 Row(index=118542, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=3870),
 Row(index=118546, ent=9, sex=2, eda=26, clase1=1, e_con=1, n_hij=1, ingocup=8600),
 Row(index=118547, ent=9, sex=2, eda=26, clase1=1, e_con=5, n_hij=2, ingocup=8000),
 Row(index=118557, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=7740),
 Row(index=118558, ent=9, sex=2, eda=26, clase1=1, e_con=1, n_hij=0, ingocup=30000),
 Row(index=118562, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=1, ingocup=5000),
 Row(index=118571, ent=9, sex=2, eda=26, clase1=1, e_con=1, n_hij=3, ingocup=3440),
 Row(index=118572, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=3870),
 Row(index=118574, ent=9, sex=2, eda=26, clase1=1, e_con=1, n_hij=0, ingocup=18000),
 Row(index=118575, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118577, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=1720),
 Row(index=118580, ent=9, sex=2, eda=26, clase1=1, e_con=1, n_hij=2, ingocup=4300),
 Row(index=118581, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=1, ingocup=16000),
 Row(index=118582, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=16000),
 Row(index=118588, ent=9, sex=2, eda=26, clase1=1, e_con=6, n_hij=0, ingocup=10000),
 Row(index=118590, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=1, ingocup=6020),
 Row(index=118592, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=15000),
 Row(index=118593, ent=9, sex=2, eda=27, clase1=1, e_con=1, n_hij=1, ingocup=1290),
 Row(index=118600, ent=9, sex=2, eda=27, clase1=1, e_con=1, n_hij=1, ingocup=6000),
 Row(index=118601, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=10750),
 Row(index=118605, ent=9, sex=2, eda=27, clase1=1, e_con=1, n_hij=2, ingocup=1500),
 Row(index=118606, ent=9, sex=2, eda=27, clase1=1, e_con=1, n_hij=3, ingocup=2150),
 Row(index=118607, ent=9, sex=2, eda=27, clase1=1, e_con=2, n_hij=2, ingocup=3440),
 Row(index=118609, ent=9, sex=2, eda=27, clase1=1, e_con=5, n_hij=1, ingocup=8600),
 Row(index=118612, ent=9, sex=2, eda=27, clase1=1, e_con=5, n_hij=0, ingocup=12900),
 Row(index=118615, ent=9, sex=2, eda=27, clase1=1, e_con=1, n_hij=2, ingocup=7000),
 Row(index=118617, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=16000),
 Row(index=118620, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=18000),
 Row(index=118624, ent=9, sex=2, eda=27, clase1=1, e_con=1, n_hij=1, ingocup=1720),
 Row(index=118626, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=13200),
 Row(index=118629, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=6000),
 Row(index=118630, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=10700),
 Row(index=118631, ent=9, sex=2, eda=27, clase1=1, e_con=1, n_hij=1, ingocup=6000),
 Row(index=118633, ent=9, sex=2, eda=27, clase1=1, e_con=5, n_hij=0, ingocup=20000),
 Row(index=118638, ent=9, sex=2, eda=27, clase1=1, e_con=2, n_hij=1, ingocup=10000),
 Row(index=118639, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=7740),
 Row(index=118640, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=1, ingocup=9000),
 Row(index=118644, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=1, ingocup=12000),
 Row(index=118646, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=30000),
 Row(index=118649, ent=9, sex=2, eda=27, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118651, ent=9, sex=2, eda=28, clase1=1, e_con=1, n_hij=2, ingocup=6000),
 Row(index=118652, ent=9, sex=2, eda=28, clase1=1, e_con=4, n_hij=1, ingocup=7525),
 Row(index=118653, ent=9, sex=2, eda=28, clase1=1, e_con=2, n_hij=2, ingocup=6000),
 Row(index=118655, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=12000),
 Row(index=118662, ent=9, sex=2, eda=28, clase1=1, e_con=1, n_hij=1, ingocup=6450),
 Row(index=118671, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=1, ingocup=10000),
 Row(index=118677, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=5000),
 Row(index=118682, ent=9, sex=2, eda=28, clase1=1, e_con=4, n_hij=2, ingocup=2580),
 Row(index=118687, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=1, ingocup=14000),
 Row(index=118696, ent=9, sex=2, eda=28, clase1=1, e_con=5, n_hij=0, ingocup=19928),
 Row(index=118697, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=1, ingocup=10000),
 Row(index=118698, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=8600),
 Row(index=118699, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=8000),
 Row(index=118706, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=7000),
 Row(index=118708, ent=9, sex=2, eda=28, clase1=1, e_con=1, n_hij=3, ingocup=3000),
 Row(index=118713, ent=9, sex=2, eda=28, clase1=1, e_con=1, n_hij=3, ingocup=6450),
 Row(index=118714, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=5000),
 Row(index=118716, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=2, ingocup=9030),
 Row(index=118718, ent=9, sex=2, eda=28, clase1=1, e_con=5, n_hij=2, ingocup=12900),
 Row(index=118720, ent=9, sex=2, eda=28, clase1=1, e_con=2, n_hij=4, ingocup=7000),
 Row(index=118728, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=7000),
 Row(index=118729, ent=9, sex=2, eda=28, clase1=1, e_con=6, n_hij=0, ingocup=10000),
 Row(index=118736, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=0, ingocup=6450),
 Row(index=118740, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=9800),
 Row(index=118744, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=19000),
 Row(index=118746, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=1, ingocup=15000),
 Row(index=118748, ent=9, sex=2, eda=29, clase1=1, e_con=2, n_hij=2, ingocup=2150),
 Row(index=118753, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=8000),
 Row(index=118754, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=30000),
 Row(index=118757, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=2, ingocup=2150),
 Row(index=118758, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=27000),
 Row(index=118761, ent=9, sex=2, eda=29, clase1=1, e_con=2, n_hij=2, ingocup=8600),
 Row(index=118762, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=1, ingocup=12000),
 Row(index=118763, ent=9, sex=2, eda=29, clase1=1, e_con=2, n_hij=4, ingocup=4300),
 Row(index=118764, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=0, ingocup=10750),
 Row(index=118768, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=2, ingocup=5160),
 Row(index=118770, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=10000),
 Row(index=118774, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=1, ingocup=7224),
 Row(index=118782, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=2, ingocup=11610),
 Row(index=118788, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=6450),
 Row(index=118791, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=1, ingocup=5000),
 Row(index=118792, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=7000),
 Row(index=118795, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=2, ingocup=5160),
 Row(index=118796, ent=9, sex=2, eda=29, clase1=1, e_con=2, n_hij=2, ingocup=9137),
 Row(index=118798, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=1, ingocup=10000),
 Row(index=118800, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=0, ingocup=30000),
 Row(index=118802, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=1, ingocup=1290),
 Row(index=118810, ent=9, sex=2, eda=29, clase1=1, e_con=1, n_hij=0, ingocup=12000),
 Row(index=118811, ent=9, sex=2, eda=29, clase1=1, e_con=6, n_hij=1, ingocup=8000),
 Row(index=118813, ent=9, sex=2, eda=30, clase1=1, e_con=6, n_hij=0, ingocup=22000),
 Row(index=118816, ent=9, sex=2, eda=30, clase1=1, e_con=6, n_hij=2, ingocup=3440),
 Row(index=118817, ent=9, sex=2, eda=30, clase1=1, e_con=6, n_hij=0, ingocup=5400),
 Row(index=118818, ent=9, sex=2, eda=30, clase1=1, e_con=6, n_hij=0, ingocup=3870),
 Row(index=118819, ent=9, sex=2, eda=30, clase1=1, e_con=1, n_hij=0, ingocup=12000),
 Row(index=118828, ent=9, sex=2, eda=30, clase1=1, e_con=6, n_hij=0, ingocup=4000),

In [70]:
filtered_rdd2.count()

2895

In [14]:
columns = df.select("ent", "sex", "eda", "clase1", "e_con", "n_hij", "ingocup")
df_filtered = columns.filter((F.col("clase1") == 1) & (F.col("n_hij").isNotNull()) & (F.col("ingocup").isNotNull()))
df_filtered2 = df_filtered.filter((F.col("ent") == 9))
df_filtered2.show()

+---+---+---+------+-----+-----+-------+
|ent|sex|eda|clase1|e_con|n_hij|ingocup|
+---+---+---+------+-----+-----+-------+
|  9|  2| 15|     1|    6|    0|   1032|
|  9|  2| 15|     1|    6|    0|   1290|
|  9|  2| 15|     1|    6|    0|   4300|
|  9|  2| 16|     1|    6|    0|   1935|
|  9|  2| 16|     1|    6|    0|   1935|
|  9|  2| 17|     1|    6|    0|   2150|
|  9|  2| 17|     1|    6|    0|   4300|
|  9|  2| 17|     1|    6|    1|   7740|
|  9|  2| 18|     1|    6|    0|   2580|
|  9|  2| 18|     1|    6|    0|   2580|
|  9|  2| 18|     1|    6|    0|   7740|
|  9|  2| 18|     1|    6|    1|   1720|
|  9|  2| 18|     1|    6|    0|   5160|
|  9|  2| 18|     1|    6|    0|   3870|
|  9|  2| 18|     1|    6|    0|   5400|
|  9|  2| 19|     1|    6|    0|   4300|
|  9|  2| 19|     1|    6|    1|   1032|
|  9|  2| 19|     1|    1|    0|   6880|
|  9|  2| 19|     1|    6|    1|   1720|
|  9|  2| 19|     1|    6|    0|   5160|
+---+---+---+------+-----+-----+-------+
only showing top 20 rows

In [194]:
#Número de hijos promedio que tiene la PEA en Nuevo León 
Nuevo = df_filtered2.select("n_hij").rdd #Convierte la filtración anterior a RDD
resultado = Nuevo.flatMap(lambda x: x) #Convierte elementos columna en elementos fila
resultado2 = resultado.reduce(lambda x, y: x + y)
Promedio = resultado2/resultado.count()
Promedio

1.6484962406015038

In [10]:
Filtro = df_with_index.filter((F.col("clase1") == 1) & (F.col("n_hij").isNotNull()) & (F.col("ingocup").isNotNull()))
Filtro2 = Filtro.filter((F.col("n_hij") == 2) & (F.col("ent") == 9))
Filtro2.show()

24/10/25 17:20:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:20:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:20:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:20:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:20:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+------+---+---+---+------+-----+-----+-------+
| index|ent|sex|eda|clase1|e_con|n_hij|ingocup|
+------+---+---+---+------+-----+-----+-------+
|118073|  9|  2| 20|     1|    6|    2|  10000|
|118130|  9|  2| 20|     1|    2|    2|   3010|
|118307|  9|  2| 23|     1|    1|    2|   6880|
|118323|  9|  2| 23|     1|    2|    2|   3440|
|118336|  9|  2| 23|     1|    6|    2|   6450|
|118372|  9|  2| 24|     1|    6|    2|   3000|
|118374|  9|  2| 24|     1|    2|    2|   2580|
|118418|  9|  2| 24|     1|    1|    2|   6450|
|118474|  9|  2| 25|     1|    6|    2|   9030|
|118482|  9|  2| 25|     1|    6|    2|   3000|
|118483|  9|  2| 25|     1|    6|    2|   7000|
|118499|  9|  2| 25|     1|    1|    2|   3440|
|118547|  9|  2| 26|     1|    5|    2|   8000|
|118580|  9|  2| 26|     1|    1|    2|   4300|
|118605|  9|  2| 27|     1|    1|    2|   1500|
|118607|  9|  2| 27|     1|    2|    2|   3440|
|118615|  9|  2| 27|     1|    1|    2|   7000|
|118651|  9|  2| 28|     1|    1|    2|   6000|
|118653|  9|  2| 28|     1|    2|    2|   6000|
|118682|  9|  2| 28|     1|    4|    2|   2580|
+------+---+---+---+------+-----+-----+-------+
only showing top 20 rows

In [16]:
df_filtered3 = df_filtered.filter((F.col("ent") == 19))
df_filtered3.show()

+---+---+---+------+-----+-----+-------+
|ent|sex|eda|clase1|e_con|n_hij|ingocup|
+---+---+---+------+-----+-----+-------+
| 19|  2| 13|     1|    6|    0|   3870|
| 19|  2| 14|     1|    6|    0|   6450|
| 19|  2| 14|     1|    6|    0|   4300|
| 19|  2| 14|     1|    6|    0|   3225|
| 19|  2| 14|     1|    6|    0|   6450|
| 19|  2| 15|     1|    6|    0|    860|
| 19|  2| 15|     1|    6|    0|    301|
| 19|  2| 15|     1|    6|    0|   1290|
| 19|  2| 16|     1|    6|    0|  12900|
| 19|  2| 16|     1|    6|    0|   2580|
| 19|  2| 16|     1|    6|    0|   2580|
| 19|  2| 16|     1|    6|    0|   6450|
| 19|  2| 16|     1|    6|    0|   6450|
| 19|  2| 16|     1|    6|    0|   5160|
| 19|  2| 17|     1|    6|    0|   7740|
| 19|  2| 17|     1|    6|    0|   6450|
| 19|  2| 17|     1|    6|    0|   7740|
| 19|  2| 17|     1|    6|    0|   9460|
| 19|  2| 17|     1|    6|    0|   1075|
| 19|  2| 17|     1|    6|    0|   7740|
+---+---+---+------+-----+-----+-------+
only showing top 20 rows

In [18]:
#Número de hijos promedio que tiene la PEA en Nuevo León 
Nuevo2 = df_filtered3.select("n_hij").rdd #Convierte la filtración anterior a RDD
resultado3 = Nuevo2.flatMap(lambda x: x) #Convierte elementos columna en elementos fila
resultado4 = resultado3.reduce(lambda x, y: x + y)
Promedio2 = resultado4/resultado3.count()
Promedio2

1.7749863462588749

In [24]:
Filtro3 = df_with_index.filter((F.col("clase1") == 1) & (F.col("n_hij").isNotNull()) & (F.col("ingocup").isNotNull()))
Filtro4 = Filtro3.filter((F.col("n_hij") == 2) & (F.col("ent") == 19))
Filtro4.show()

24/10/25 17:58:36 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:58:36 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:58:36 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+------+---+---+---+------+-----+-----+-------+
| index|ent|sex|eda|clase1|e_con|n_hij|ingocup|
+------+---+---+---+------+-----+-----+-------+
|246599| 19|  2| 18|     1|    1|    2|    860|
|246854| 19|  2| 20|     1|    5|    2|   6000|
|246909| 19|  2| 20|     1|    6|    2|   7310|
|246912| 19|  2| 20|     1|    2|    2|   1935|
|246978| 19|  2| 21|     1|    1|    2|   4300|
|246996| 19|  2| 21|     1|    1|    2|   6600|
|247047| 19|  2| 21|     1|    1|    2|   2000|
|247094| 19|  2| 22|     1|    1|    2|   7310|
|247180| 19|  2| 22|     1|    5|    2|   8600|
|247312| 19|  2| 23|     1|    1|    2|  10750|
|247318| 19|  2| 23|     1|    2|    2|   9890|
|247346| 19|  2| 24|     1|    1|    2|   1290|
|247376| 19|  2| 24|     1|    5|    2|  21500|
|247380| 19|  2| 24|     1|    2|    2|   5590|
|247395| 19|  2| 24|     1|    1|    2|   3440|
|247403| 19|  2| 24|     1|    5|    2|   8000|
|247417| 19|  2| 24|     1|    2|    2|   4300|
|247428| 19|  2| 24|     1|    5|    2|   8600|
|247429| 19|  2| 24|     1|    1|    2|   8600|
|247438| 19|  2| 25|     1|    6|    2|   8600|
+------+---+---+---+------+-----+-----+-------+
only showing top 20 rows

24/10/25 17:58:36 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
24/10/25 17:58:36 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.